services:
  cli-proxy-api:
    image: eceasy/cli-proxy-api:latest
    pull_policy: always
    command: ["/CLIProxyAPI/CLIProxyAPI", "--config", "/data/config.yaml"]
    environment:
      DEPLOY: cloud
      TZ: Asia/Shanghai
      MANAGEMENT_STATIC_PATH: /data/static
    expose:
      - "8317"
    volumes:
      - ../files/config.yaml:/data/config.yaml:ro
      - cli-proxy-auths:/data/auths
      - cli-proxy-static:/data/static
    restart: unless-stopped

volumes:
  cli-proxy-auths:
  cli-proxy-static:
